language: perl

before_install:
  - sudo apt-get install gfortran
  - sudo apt-get install fp-compiler-2.4.4
  - sudo apt-get install g++
  - sudo apt-get install gcj-jdk
  - sudo apt-get install libgtop2-7

install:
  - cpanm -n Alien::FFI
  - cpanm -n ExtUtils::CBuilder
  - cpanm -n Config::AutoConf
  - cpanm -n FFI::CheckLib
  - cpanm -n Math::Int64
  - cpanm -n File::chdir
  - cpanm -n Convert::Binary::C
  - cpanm -n Time::Seconds

perl:
  - "5.8"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"

script:
  - perl Build.PL
  - perl inc/run/travis.pl
  - ./Build --verbose
  - ./Build test --verbose
  - ./Build install --verbose
  
  - cpanm -n --installdeps FFI::Platypus::Type::StringArray
  - cpanm -v FFI::Platypus::Type::StringArray

  - cpanm -n --installdeps FFI::TinyCC
  - cpanm -v FFI::TinyCC

  - perl inc/run/test_examples.pl

  - cpanm -n --installdeps FFI::Util
  - cpanm -v FFI::Util
  - cpanm -n --installdeps UUID::FFI
  - cpanm -v UUID::FFI
  - cpanm -n --installdeps Phash::FFI
  - cpanm -v Phash::FFI
  - cpanm -n --installdeps Acme::Ford::Prefect::FFI
  - cpanm -v Acme::Ford::Prefect::FFI
  - cpanm -n --installdeps File::LibMagic::FFI
  - cpanm -v File::LibMagic::FFI

  - cpanm -n --installdeps FFI::Platypus::Lang::CPP
  - cpanm -v FFI::Platypus::Lang::CPP
  - cpanm -n --installdeps FFI::Platypus::Lang::Fortran
  - cpanm -v FFI::Platypus::Lang::Fortran
  - cpanm -n --installdeps FFI::Platypus::Lang::Pascal
  - cpanm -v FFI::Platypus::Lang::Pascal
  - cpanm -n --installdeps FFI::Platypus::Lang::Rust
  - cpanm -v FFI::Platypus::Lang::Rust

env:
  - FFI_PLATYPUS=1
  - FFI_PLATYPUS_DEBUG_FAKE32=1
  - FFI_PLATYPUS_NO_ALLOCA=1
  - FFI_PLATYPUS_DEBUG_FAKE32=1 FFI_PLATYPUS_NO_ALLOCA=1
