language: perl

sudo: true

before_install:
  - sudo apt-get install gfortran
  - sudo apt-get install fp-compiler-2.4.4
  - sudo apt-get install g++
  - sudo apt-get install gcj-jdk
  - sudo apt-get install libgtop2-7

install:
  - cpanm -n constant
  - cpanm -n Alien::FFI
  - cpanm -n ExtUtils::CBuilder
  - cpanm -n Config::AutoConf
  - cpanm -n FFI::CheckLib
  - cpanm -n Math::Int64
  - cpanm -n File::chdir
  - cpanm -n Convert::Binary::C
  - cpanm -n Time::Seconds
  - cpanm -n Devel::PPPort
  - cpanm -n local::lib

perl:
  - "5.8"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.18-shrplib"
  - "5.20"
  - "5.20-shrplib"

script:
  - perl Build.PL
  - perl inc/run/travis.pl
  - ./Build --verbose
  - ./Build test --verbose
  - ./Build install --verbose

  - perl inc/run/travis_cpan.pl FFI::Util
  - perl inc/run/travis_cpan.pl FFI::TinyCC
  - perl inc/run/travis_cpan.pl FFI::ExtractSymbols
  
  - perl inc/run/travis_cpan.pl UUID::FFI
  - perl inc/run/travis_cpan.pl Phash::FFI
  - perl inc/run/travis_cpan.pl Acme::Ford::Prefect::FFI
  - perl inc/run/travis_cpan.pl File::LibMagic::FFI
  #- perl inc/run/travis_cpan.pl Archive::Libarchive::FFI
  - cpanm -n Math::BigInt
  - perl inc/run/travis_cpan.pl ZMQ::FFI

  - perl inc/run/travis_cpan.pl FFI::Platypus::Lang::CPP
  - perl inc/run/travis_cpan.pl FFI::Platypus::Lang::Fortran
  - perl inc/run/travis_cpan.pl FFI::Platypus::Lang::Pascal
  - perl inc/run/travis_cpan.pl FFI::Platypus::Lang::Rust
  
  - perl inc/run/travis_cpan.pl FFI::Platypus::Type::StringArray

  - perl inc/run/test_examples.pl

env:
  - FFI_PLATYPUS=1
  - FFI_PLATYPUS_DEBUG_FAKE32=1
  - FFI_PLATYPUS_NO_ALLOCA=1
  - FFI_PLATYPUS_DEBUG_FAKE32=1 FFI_PLATYPUS_NO_ALLOCA=1
